### ISSUE TITLE
Gallery on Products/Variations

### ISSUE THREAD

**Issue by RichardKBR** [Knawat/featured-image-by-url#16]
Hi. Product/Variations doesn't have gallery? Or i doing something wrong? de post work on product, creates a gallery and a feature image . But doesn't work on variations. 

Thank you!

**Comment by sunil11475** [comment]
You have play with "product-thumbnails.php" file to work with variation images - 

add "product-thumbnails.php" in to your /themes/YOURTHEME/woocommerce/single-product/

IF not showing the gallery image then check the code source - (Bootstrap issue)
Make sure add "remove_theme_support( 'wc-product-gallery-slider' );" without double quote into your theme function.php

Because "wc-product-gallery-slider" marking variation images display:none.

**Comment by RichardKBR** [comment]
Hi sunil11475. I'll try to explain. This is main product:


![image](https://user-images.githubusercontent.com/12806346/50103402-b0c4dc80-020e-11e9-99ea-0a5b0241d1f8.png)


When i change/select variation, olny show 1 (one) image of variation. Does not show all imagens in the variation object.


![image](https://user-images.githubusercontent.com/12806346/50103652-3fd1f480-020f-11e9-8c4c-701df4b89d0a.png)


JSON of varition is like:

"meta_data": [
        {            
            "key": "_knawatfibu_wcgallary",
            "value": [
                {
                    "url": "http://compumate.com.br/temp/teste5.png",
                    "width": 1000,
                    "height": 1000
                },
                {
                    "url": "http://compumate.com.br/temp/teste4.png",
                    "width": 1000,
                    "height": 1000
                },
                {
                    "url": "http://compumate.com.br/temp/teste3.png",
                    "width": 1000,
                    "height": 1000
                }                
            ]
        }
]

**Comment by iamdharmesh** [comment]
Hello @RichardKBR,

Thanks for creating issue.

WooCommerce doesn't provide gallery support for variations. So, as per your screenshot its an expected behavior of plugin. You can add gallery support to variations by using third-party plugin but WooCommerce itself not provide gallery support for variations. 

Let us know if you have any other difficulties and feel free to open this issue if you need any additional help for the same.

Thanks,
Dharmesh Patel
