### ISSUE TITLE
No more images in cart after upgrade to WC 3.5

### ISSUE THREAD

**Issue by finalwebsites** [Knawat/featured-image-by-url#19]
Hi,
After an upgrade to WooCommerce 3.5.x the thumbnail disappeared from the cart page.
Looks like the WP filter isn't working anymore. I did a rollback to WC version 3.4.7 and the images are back again. Any idea? Someone else with the same issue?

**Comment by iamdharmesh** [comment]
Hello @finalwebsites,

Thanks for creating issue.

We haven't faced issue like this after upgrade to WC 3.5. Maybe its because of theme. can you please try using temporary switching to one of default theme of WP and let me know its working fine or not. Also, which theme you are using.?

Thanks,
Dharmesh Patel
