### ISSUE TITLE
Import/Export Featured Images by URL via CSV

### ISSUE THREAD

**Issue by tierrioliveira** [Knawat/featured-image-by-url#8]
Hi there,

Your plugin works really fine in my template, I'm really thankful for it. I'd like to suggest one improvement: it would be great if we could import/export those links via CSV. Currently, we can only add those links manually so if we have thousands of images it's difficult to process them.

Thanks again!

**Comment by iamdharmesh** [comment]
Hello @tierrioliveira,

Thanks for suggesting improvement. Yes, currently we don't have a functionality for a CSV import because its not very common that import/export only featured image URL by CSV files. Generally people import/export it with post or CPT imports. So, you can import Featured image by URL into custom post meta field by import/export functionality. custom field for featured image is ` _knawatfibu_url` so you can use it. 

Don't know your use-case how do you want to use it but happy to help you if you share.

Thanks.

**Comment by nimamox** [comment]
Is there any plan to support this? I wanted to open an issue but realized that @tierrioliveira has already reported this. I use the CSV importer since importing through the REST API takes a lot of time, so bulk importing via CSV is a better option.

**Comment by vegantraveler** [comment]
Hi, I was able to do mass import from my CSV file using 'wp all import' plugin by grabbing the custom field '_knawatfibu_url' under the key 'img_url' (you can auto detect, or put manually as serialized) and even added one image to the gallery using the '_knawatfibu_wcgallary' custom field under the key 'url', now, how could I add several images to that '_knawatfibu_wcgallary' custom field? 

I already tried adding several image URLs separated by comma, but that didn't work...

Any suggestion?
<img width="843" alt="Screen Shot 2021-02-16 at 1 28 27 PM" src="https://user-images.githubusercontent.com/38513704/108105766-06011080-705b-11eb-98e6-7544299403a8.png">
